#!/usr/bin/perl -w

# 2010-03-13 to 2010-03-17 mza @ uh idlab

use strict;
#BEGIN {
#	my $localdir = $ENV{0};
#	print $localdir . "\n";
#	$localdir =~ s/\/.*//;
#	print $localdir . "\n";
#	exit(0);
#}
use Tk;
use Tk::PNG;
use Tk::Photo;
use lib '/home/pilas/build/motor';
use motor_controller;
use debug_info_warning_error;

#my $gui_has_been_instantiated = 0;

my $displayed_delay_in_picoseconds            = 0; # 0 to 1000
my $displayed_delay_in_picoseconds_scale      = 0; # 0 to 1000
#my $displayed_delay_slide_macrostep_position  = 0; # 0 to 20
my $displayed_filter_slide_macrostep_position = 0; # 0 to 4

my $delay_setting_precision_in_picoseconds = 1;
my $delay_setting_precision_in_macrosteps = $delay_setting_precision_in_picoseconds / $delay_slide_granularity_in_picoseconds;

my $window;
my ($radiobutton_filter_none, $radiobutton_filter_one, $radiobutton_filter_two, $radiobutton_filter_three, $radiobutton_filter_four);
my ($button_delay_increment, $button_delay_decrement, $entry_delay_in_picoseconds);
my ($frame_for_delay_in_picoseconds, $entry_delay_units);
#my $label_delay_corresponding_to_number_of_desired_macrosteps;

my ($should_draw_filter_slide_frame, $should_draw_delay_slide_frame, $should_draw_x_frame, $should_draw_y_frame) = (1, 1, 1, 1);

sub setup_main_window {
	$window = new MainWindow(-title=>"PiLas motor controller");

	my $filter_slide_frame;
	my $delay_slide_frame;
	my $delay_slide_frame_1;
	my $delay_slide_frame_2;
	my $radiobutton_filter_label;
	my $scale_delay_in_picoseconds;
	my $button_go;
	my $button_reset_delay_slide;
	my $button_find_limits;
	my $default_color = "#d9d9d9";
	my ($filter_slide_frame_background_color, $delay_slide_frame_background_color) = ($default_color, $default_color);
	#$filter_slide_frame_background_color = "#efefef";
	#$delay_slide_frame_background_color = "#dfdfdf";
	my $frame_xy_slide_grid_background_color = "#d9d9d9";
	my $delay_slide_frame_label;

#	($should_draw_filter_slide_frame, $should_draw_delay_slide_frame, $should_draw_x_frame, $should_draw_y_frame) = (0, 0, 1, 1);
	if ($should_draw_filter_slide_frame) {
		$filter_slide_frame  = $window->Frame(-borderwidth=>15, -background=>$filter_slide_frame_background_color);
		$radiobutton_filter_label = $filter_slide_frame->Label(-text=>"filter slide:", -background=>$filter_slide_frame_background_color);
		$radiobutton_filter_none  = $filter_slide_frame->Radiobutton(-text=>"none",  -value=>0, -variable=>\$displayed_filter_slide_macrostep_position, -command=>\&filter_slide_radiobutton_clicked, -background=>$filter_slide_frame_background_color);
		$radiobutton_filter_one   = $filter_slide_frame->Radiobutton(-text=>"one",   -value=>1, -variable=>\$displayed_filter_slide_macrostep_position, -command=>\&filter_slide_radiobutton_clicked, -background=>$filter_slide_frame_background_color);
		$radiobutton_filter_two   = $filter_slide_frame->Radiobutton(-text=>"two",   -value=>2, -variable=>\$displayed_filter_slide_macrostep_position, -command=>\&filter_slide_radiobutton_clicked, -background=>$filter_slide_frame_background_color);
		$radiobutton_filter_three = $filter_slide_frame->Radiobutton(-text=>"three", -value=>3, -variable=>\$displayed_filter_slide_macrostep_position, -command=>\&filter_slide_radiobutton_clicked, -background=>$filter_slide_frame_background_color);
		$radiobutton_filter_four  = $filter_slide_frame->Radiobutton(-text=>"four",  -value=>4, -variable=>\$displayed_filter_slide_macrostep_position, -command=>\&filter_slide_radiobutton_clicked, -background=>$filter_slide_frame_background_color);
		$radiobutton_filter_label->grid(-row=>0, -column=>0);
		$radiobutton_filter_none->grid (-row=>1, -column=>0);
		$radiobutton_filter_one->grid  (-row=>2, -column=>0);
		$radiobutton_filter_two->grid  (-row=>3, -column=>0);
		$radiobutton_filter_three->grid(-row=>4, -column=>0);
		$radiobutton_filter_four->grid (-row=>5, -column=>0);
		$filter_slide_frame->grid(-row=>0, -column=>0);
	}
	if ($should_draw_delay_slide_frame) {
		$delay_slide_frame                = $window->Frame(-borderwidth=>15, -background=>$delay_slide_frame_background_color);
		$delay_slide_frame_1              = $delay_slide_frame->Frame(-background=>$delay_slide_frame_background_color);
		$delay_slide_frame_label          = $delay_slide_frame_1->Label(-text=>"delay slide:", -background=>$delay_slide_frame_background_color);
		$button_reset_delay_slide         = $delay_slide_frame_1->Button(-text=>"reset delay slide", -command=>\&reset_delay_slide, -background=>$delay_slide_frame_background_color);
		$button_delay_decrement           = $delay_slide_frame_1->Button(-text=>"decrease delay by 50ps",  -command=>\&decrease_delay_slide_by_one_granule, -background=>$delay_slide_frame_background_color);
		$entry_delay_in_picoseconds       = $delay_slide_frame_1->Entry(-width=>5, -state=>"normal", -textvariable=>\$displayed_delay_in_picoseconds, -background=>$delay_slide_frame_background_color);
		#, -validatecommand=>\&desired_delay_has_possibly_changed);
		$entry_delay_units                = $delay_slide_frame_1->Label(-text=>"ps", -background=>$delay_slide_frame_background_color);
		$button_delay_increment           = $delay_slide_frame_1->Button(-text=>"increase delay by 50ps",  -command=>\&increase_delay_slide_by_one_granule, -background=>$delay_slide_frame_background_color);
	#	$button_find_limits               = $delay_slide_frame_1->Button(-text=>"find limits of motion",  -command=>\&get_limits_of_motion, -background=>$delay_slide_frame_background_color);
		
	$delay_slide_frame_2   = $delay_slide_frame->Frame(-background=>$delay_slide_frame_background_color);
		$scale_delay_in_picoseconds       = $delay_slide_frame_2->Scale(-orient=>"h", -digit=>1, -variable=>\$displayed_delay_in_picoseconds_scale, -from=>0, -to=>1000, -tickinterval=>250, -command=>\&desired_delay_has_possibly_changed, -length=>325, -resolution=>50, -background=>$delay_slide_frame_background_color);
		# -bigincrement=>3 -label=>"delay", 
	#	$scale_delay_in_picoseconds       = $delay_slide_frame_2->Scale(-label=>"delay", -orient=>"v", -digit=>1, -variable=>\$displayed_delay_in_picoseconds, -from=>\$motor_controller::smallest_delay_in_ps, -to=>\$motor_controller::largest_delay_in_ps, -tickinterval=>\$motor_controller::delay_slide_granularity_in_picoseconds);
	#	$label_delay_corresponding_to_number_of_desired_macrosteps = $delay_slide_frame_2->Label(-text=>"", -width=>10);
		$button_go                        = $delay_slide_frame_2->Button(-text=>"go", -command=>\&predicate_new_desired_delay_in_picoseconds_scale, -background=>$delay_slide_frame_background_color);

		$scale_delay_in_picoseconds->grid    (-row=>0, -column=>0, -columnspan=>3);
#		$label_delay_corresponding_to_number_of_desired_macrosteps->grid(-row=>0, -column=>3);
		$button_go->grid                     (-row=>0, -column=>4);
		$delay_slide_frame_label->grid       (-row=>0, -column=>0, -columnspan=>5);
		$button_reset_delay_slide->grid      (-row=>1, -column=>0);
		$button_delay_decrement->grid        (-row=>1, -column=>1);
		$entry_delay_in_picoseconds->grid    (-row=>1, -column=>2);
		$entry_delay_units->grid             (-row=>1, -column=>3);
		$button_delay_increment->grid        (-row=>1, -column=>4);
#		$button_find_limits->grid            (-row=>1, -column=>5);
		$delay_slide_frame_1->grid(-row=>0, -column=>0);
		$delay_slide_frame_2->grid(-row=>1, -column=>0);
		$delay_slide_frame->grid (-row=>0, -column=>1);
		$entry_delay_in_picoseconds->bind('<Return>', \&predicate_new_desired_delay_in_picoseconds);
	}
	my $frame_xy_slide_grid;
	if ($should_draw_x_frame && $should_draw_y_frame) {
		$frame_xy_slide_grid = $window->Frame(-borderwidth=>15, -background=>$frame_xy_slide_grid_background_color);
		my $frame_xy_slide_grid_get_out_of_way_button  = $frame_xy_slide_grid->Button(-text=>"save x position and get out of way of PMT",  -command=>\&save_position_and_move_x_slide_out_of_way, -background=>$frame_xy_slide_grid_background_color);
		my $frame_xy_slide_grid_restore_position_button  = $frame_xy_slide_grid->Button(-text=>"restore x position",  -command=>\&restore_position_of_x_slide, -background=>$frame_xy_slide_grid_background_color);
		$frame_xy_slide_grid_get_out_of_way_button->grid   (-row=>1, -column=>0);
		$frame_xy_slide_grid_restore_position_button->grid (-row=>2, -column=>0);
		my $frame_xy_slide_grid_left_button  = $frame_xy_slide_grid->Button(-text=>"left",  -command=>[\&move_xy_slide, -1,  0], -background=>$frame_xy_slide_grid_background_color);
		my $frame_xy_slide_grid_right_button = $frame_xy_slide_grid->Button(-text=>"right", -command=>[\&move_xy_slide, +1,  0], -background=>$frame_xy_slide_grid_background_color);
		my $frame_xy_slide_grid_up_button    = $frame_xy_slide_grid->Button(-text=>"up",    -command=>[\&move_xy_slide,  0, +1], -background=>$frame_xy_slide_grid_background_color);
		my $frame_xy_slide_grid_down_button  = $frame_xy_slide_grid->Button(-text=>"down",  -command=>[\&move_xy_slide,  0, -1], -background=>$frame_xy_slide_grid_background_color);
		$frame_xy_slide_grid_left_button->grid (-row=>1, -column=>3+0);
		$frame_xy_slide_grid_right_button->grid(-row=>1, -column=>3+2);
		$frame_xy_slide_grid_up_button->grid   (-row=>0, -column=>3+1);
		$frame_xy_slide_grid_down_button->grid (-row=>2, -column=>3+1);
		if (0) {
			my $frame_canvas = $frame_xy_slide_grid->Canvas(-width=>313, -height=>320);
			my $image = $frame_canvas->Photo(-format=>"png", -file => "R5900.png", -width=>313, -height=>320);
			$frame_canvas->create('image', 0, 0, '-anchor' => 'nw', '-image' => $image);
			$frame_canvas->grid(-row=>0, -column=>0);
			$frame_canvas->Tk::bind('<ButtonRelease-1>', \&grid_button_release);
		}
		$frame_xy_slide_grid->grid(-row=>1, -column=>0, -columnspan=>2);
	}
	$window->bind('<Key-Escape>', \&quit);
}

#sub save_position_and_move_x_slide_out_of_way {
#	motor_controller::save_position_and_move_x_slide_out_of_way();
#}

#sub restore_position_of_x_slide {
#	motor_controller::restore_position_of_x_slide();
#}

sub move_xy_slide {
	my ($delta_x, $delta_y) = @_;
#	print "($delta_x, $delta_y)\n";
	move_xy_slide_to_granular_relative_position($delta_x, $delta_y);
}

sub grid_button_release {
	my ($widget) = @_;
	my $event = $widget->XEvent;
	my ($screen_x, $screen_y, $window_x, $window_y) = ($event->X, $event->Y, $event->x, $event->y);
#	print "grid button release @ " . $x . "x" . $y . "+" . $w . "+" . $h . "\n";
#	print "grid button release @ " . $screen_x . "x" . $screen_y . "+" . $window_x . "+" . $window_y . "\n";
	print "grid button release @ " . $window_x . "x" . $window_y . "\n";
	my ($x_offset, $x_gain, $y_offset, $y_gain) = (59, 25.0, 57, 25.0);
	my $x = ($window_x - $x_offset) / $x_gain;
	my $y = ($window_y - $y_offset) / $y_gain;
#	print "($window_x, $window_y) -> [$x,$y]\n";
	if (0.0 < $x && $x < 8.0 && 0.0 < $y && $y < 8.0) {
		$x = int($x);
		$y = int($y);
		print "[$x,$y]\n";
	}
}

sub quit {
	exit(0);
}

sub increase_delay_slide_by_one_granule {
	increase_delay_slide_by_one_macrostep();
	update_delay_in_picoseconds(current_delay_in_whole_picoseconds());
}

sub decrease_delay_slide_by_one_granule {
	decrease_delay_slide_by_one_macrostep();
	update_delay_in_picoseconds(current_delay_in_whole_picoseconds());
}

sub reset_delay_slide {
	bring_delay_slide_to_beginning();
	update_delay_in_picoseconds(current_delay_in_whole_picoseconds());
}

sub desired_delay_has_possibly_changed {
	my $current_delay = current_delay_in_picoseconds();
	if ($delay_setting_precision_in_picoseconds <= abs($displayed_delay_in_picoseconds - $current_delay)) {
#		print "desired delay in picoseconds has changed\n";
		info("current delay = " . $current_delay . " ps");
		info("desired delay = " . $displayed_delay_in_picoseconds . " ps");
		update_delay_in_picoseconds_scale();
	}
	my $current_delay_macrostep_position = current_macrostep_position_of_delay_slide();
#	if ($delay_setting_precision_in_macrosteps <= abs($displayed_delay_slide_macrostep_position - $current_delay_macrostep_position)) {
#	if ($displayed_delay_slide_macrostep_position != current_whole_macrostep_position_of_delay_slide()) {
#		print "desired delay slide position has changed\n";
#		info("current delay slide position = " . delay_macrosteps_steps_and_picoseconds_from_macrosteps(current_whole_macrostep_position_of_delay_slide()));
#		info("desired delay slide position = " . delay_macrosteps_steps_and_picoseconds_from_macrosteps($displayed_delay_slide_macrostep_position));
#		update_label_delay_corresponding_to_number_of_desired_macrosteps();
#	}
}

#sub update_label_delay_corresponding_to_number_of_desired_macrosteps {
#	my $delay_in_picoseconds = absolute_macrosteps_to_absolute_picoseconds($displayed_delay_slide_macrostep_position);
#	$label_delay_corresponding_to_number_of_desired_macrosteps->configure(-text=>$delay_in_picoseconds . " ps");
#}

sub predicate_new_desired_delay_in_picoseconds {
	move_delay_slide_to_this_delay_in_picoseconds($displayed_delay_in_picoseconds);
	update_delay_in_picoseconds(current_delay_in_whole_picoseconds());
}

sub predicate_new_desired_delay_in_picoseconds_scale {
	$displayed_delay_in_picoseconds = $displayed_delay_in_picoseconds_scale;
	predicate_new_desired_delay_in_picoseconds();
}

#sub predicate_new_desired_delay_in_macrosteps {
#	move_delay_slide_to_macrostep_position($displayed_delay_slide_macrostep_position);
#	update_delay_in_picoseconds(current_delay_in_whole_picoseconds());
#}

sub filter_slide_radiobutton_clicked {
#filter_macrosteps_and_steps_from_macrosteps(current_macrostep_position_of_filter_slide())
#	print "$displayed_filter_macrostep_slide_position, $current_filter_slide_macrostep_position\n";
	if ($displayed_filter_slide_macrostep_position != current_macrostep_position_of_filter_slide()) {
		if ($displayed_filter_slide_macrostep_position == 0) {
#			move_filter_slide_to_macrostep_position($displayed_filter_slide_macrostep_position);
			bring_filter_slide_to_beginning();
		} else {
			move_filter_slide_to_macrostep_position($displayed_filter_slide_macrostep_position);
		}
	}
}

sub update_delay_in_picoseconds_scale {
	$displayed_delay_in_picoseconds_scale = $displayed_delay_in_picoseconds;
}

sub update_delay_in_picoseconds {
	my ($new_delay_in_picoseconds) = @_; 
	$displayed_delay_in_picoseconds       = $new_delay_in_picoseconds;
	update_delay_in_picoseconds_scale();
}

#get_limits_of_motion(); quit(7);

setup_main_window();
update_delay_in_picoseconds(current_delay_in_whole_picoseconds());
$displayed_filter_slide_macrostep_position = current_macrostep_position_of_filter_slide();
#update_label_delay_corresponding_to_number_of_desired_macrosteps();
MainLoop;

